var relX,relY,canvas=document.getElementById("gridSpace"),ctx=canvas.getContext("2d"),isClicked=!1,drawList=[],numTiles=0,isSolved=!1,drawer,board;$("body").on("contextmenu","#gridSpace",function(a){return!1});$(document).keydown(function(a){var b=a.keyCode?a.keyCode:a.which;if(0==b||9==b)a.preventDefault(),a.stopPropagation()});$("#gridSpace").mousemove(function(a){var b=$(this).parent().offset();relX=a.pageX-b.left;relY=a.pageY-b.top});
$("#gridSpace").click(function(a){board.setMouseCell();board.alpha=.99;$("#mobile").focus();$("#mobile").val("")});$(document).ready(function(){$("#mobile").focus();$("body").keydown(function(a){9==a.which&&(isSolved?init():solve())})});
$(document).ready(function(){$("body").keyup(function(a){a=a.which-48;$("#mobile").focus();switch(a){case -35:isSolved?init():solve();break;case -40:board.remove();isSolved=!1;break;case -11:board.moveCursor("l");break;case -9:board.moveCursor("r");break;case -8:board.moveCursor("d");break;case -10:board.moveCursor("u")}9>=a&&0<a&&board.fillCell(a)})});function dist(a,b,c,d){return Math.sqrt(Math.pow(c-a,2)+Math.pow(d-b,2))}
function Tile(a,b,c){this.X=a;this.Y=b;this.num=c;this.id=numTiles;this.color="#000000";numTiles++}Tile.prototype={draw:function(){this.isVisible&&(this.X=relX,this.Y=relY);ctx.fillStyle=this.color;ctx.font="30px serif";ctx.fillText(this.num,this.X-5,this.Y+5)},setColor:function(a){this.color=a}};function SolvedTile(a,b,c){Tile.call(this,a,b,c);this.color="#ff0000"}SolvedTile.prototype=Object.create(Tile.prototype);
function Drawer(){this.drawList=[];this.moveToFront=function(a){a=this.drawList.splice(a,1)[0];this.drawList.push(a)};this.remove=function(a){for(var b,c=0;c<this.drawList.length;c++)b=this.drawList[c],b.id==a&&this.drawList.splice(c,1)}}
function Board(){this.y=this.x=0;this.vals=[];for(var a=[],b,c,d=0;9>d;d++){for(var e=0;9>e;e++)b=Math.floor(e/9*800)+40,c=Math.floor(d/9*800)+40,a.push(new Tile(b,c,0));this.vals.push(a);a=[]}this.remove=function(){var a=this.vals[this.y][this.x];a.num=0;drawer.remove(a.id)};this.moveCursor=function(a){switch(a){case "l":0<this.x&&this.x--;break;case "r":8>this.x&&this.x++;break;case "u":0<this.y&&this.y--;break;case "d":8>this.y&&this.y++}};this.alpha=1;this.setMouseCell=function(){800<relX||800<
relY?this.y=this.x=null:(this.x=Math.floor(relX/800*9),this.y=Math.floor(relY/800*9))};this.fillCell=function(a){0==this.vals[this.y][this.x].num?(this.vals[this.y][this.x].num=a,drawer.drawList.push(this.vals[this.y][this.x])):this.vals[this.y][this.x].num=a};this.drawBoard=function(){drawBackground();if(null!=this.x&&null!=this.y){var a=Math.floor(this.x/9*800)+5,b=Math.floor(this.y/9*800)+5;ctx.beginPath();ctx.fillStyle="rgba(200,200,200,"+this.alpha+")";ctx.fillRect(a,b,80,80);ctx.closePath()}};
var f=-.03;this.flashCell=function(){this.alpha+=f;if(0>=this.alpha||1<=this.alpha)f=-f}}function drawBackground(){for(var a=1,b=0;9>=b;b++)a=0==b||0==b%3?5:1,ctx.beginPath(),ctx.moveTo(800*b/9,0),ctx.lineTo(800*b/9,800),ctx.lineWidth=a,ctx.stroke(),ctx.moveTo(0,800*b/9),ctx.lineTo(800,800*b/9),ctx.lineWidth=a,ctx.stroke(),ctx.closePath()}function init(){drawer=new Drawer;board=new Board;numTiles=0;isSolved=!1}
function main(){ctx.clearRect(0,0,canvas.width,canvas.height);board.drawBoard();for(var a=0;a<drawer.drawList.length;a++)drawer.drawList[a].draw();board.flashCell();requestAnimationFrame(main)}var list=[];
function solve(){board.alpha=.01;list=[];for(var a=0;9>a;a++)for(var b=0;9>b;b++)list.push(board.vals[a][b].num);a=new Solver(list);isSolved=a.solve();var c=a.getGrid(),d;if(isSolved)for(a=0;9>a;a++)for(b=0;9>b;b++){d=board.vals[a][b];var e=d.num;d.num=c[a][b];0==e&&(d.setColor("#DF2079"),drawer.drawList.push(d))}else alert("Bad Puzzle")};
